FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
ENV NODE_OPTIONS="--max-old-space-size=1536"
RUN npm ci --prefer-offline --no-audit --no-fund

COPY prisma ./prisma
RUN npx prisma generate

COPY src/lib ./src/lib
COPY src/features ./src/features
COPY src/workers ./src/workers
COPY tsconfig.json ./

CMD ["npx", "tsx", "src/workers/index.ts"]
